services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: TimeTracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - time_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d TimeTracker"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: ./src
      dockerfile: TimeTracker.Api/Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=db;Port=5432;Database=TimeTracker;Username=admin;Password=admin
    
     # JWT
      Auth__Jwt__Issuer: TimeTracker
      Auth__Jwt__Audience: TimeTracker
      Auth__Jwt__Key: "${JWT_KEY}"
      Auth__Jwt__ExpiresMinutes: "120"

      # GitHub OAuth
      GitHub__ClientId: "${GITHUB_CLIENT_ID}"
      GitHub__ClientSecret: "${GITHUB_CLIENT_SECRET}"
      GitHub__CallbackPath: "/api/v1/auth/github/callback"

      # GitHubApp
      GitHubApp__PrivateKeyPath: "${GITHUBAPP__PRIVATEKEYPATH}"
      GitHubApp__AppId: "${GITHUBAPP__APPID}"
      GitHubApp__ClientId: "${GITHUBAPP__CLIENTID}"
      GitHubApp__ClientSecret: "${GITHUBAPP__CLIENTSECRET}"
      GitHubApp__WebhookSecret: "${GITHUBAPP__WEBHOOKSECRET}"
      GitHubApp__BaseUrl: "${GITHUBAPP__BASEURL}"
      GitHubApp__AppSlug: "${GITHUBAPP__APPSLUG}"
      
    ports:
      - "8080:8080"
    volumes:
    - ./src/TimeTracker.Api/secrets:/run/secrets/github:ro
    restart: unless-stopped

volumes:
  time_pgdata:
